name: golang-test

on:
  pull_request:

jobs:
  gotest:
    name: gotest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
      - name: Go Build
        run: go build -v ./.

      - name: Go Test
        run: go test -v -run '' -timeout 10m ./...